CREATE TABLE SALON (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	NAZIV varchar(50) NOT NULL,
	ADRESA varchar(50),
	TELEFON varchar(20),
	EMAIL varchar(30),
	WEBSAJT varchar(30),
	PIB INT,
	MATICNI_BR INT,
	BR_RACUNA varchar(30),
	OBRISAN BIT NOT NULL
)
GO


CREATE TABLE TIP_NAMESTAJA (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	NAZIV varchar(50) NOT NULL,
	OBRISAN BIT NOT NULL
)
GO

CREATE TABLE AKCIJA (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	NAZIV varchar(50) NOT NULL,
	DATUM_OD DATE NOT NULL,
	DATUM_DO DATE NOT NULL,
	POPUST INT NOT NULL,
	OBRISAN BIT NOT NULL
	)
GO

CREATE TABLE NAMESTAJ (
	ID INT PRIMARY KEY IDENTITY(1, 1),	
	NAZIV varchar(50) NOT NULL,
	KOLICINA_MAG INT NOT NULL,
	CENA NUMERIC(9, 2) NOT NULL,
	TIP_NAMESTAJA_ID INT NOT NULL,
	AKCIJA_ID INT NULL,
	OBRISAN BIT NOT NULL,
	FOREIGN KEY (TIP_NAMESTAJA_ID) REFERENCES TIP_NAMESTAJA(ID)	
)
GO

CREATE TABLE DODATNE_USLUGE (
	ID INT PRIMARY KEY IDENTITY(1, 1),	
	NAZIV varchar(50) NOT NULL,
	CENA NUMERIC(9, 2) NOT NULL,
	OBRISAN BIT NOT NULL
	)
	GO


CREATE TABLE PRODAJA (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	BR_RACUNA varchar(10) NOT NULL,
	DATUM DATE NOT NULL,
	KUPAC varchar(50) NOT NULL,
	UKUPNA_CENA NUMERIC(9, 2) NOT NULL,
	ID_DODATNE_USLUGE INT NULL,
	OBRISAN BIT NOT NULL
)
GO

CREATE TABLE PRODAJA_STAVKE (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	PRODAJA_ID INT NOT NULL,
	NAMESTAJ_ID INT NOT NULL,
	KOLICINA INT NOT NULL,
	OBRISAN BIT NOT NULL
	FOREIGN KEY (PRODAJA_ID) REFERENCES PRODAJA(ID),
	FOREIGN KEY (NAMESTAJ_ID) REFERENCES NAMESTAJ(ID)
)
GO


CREATE TABLE KORISNIK (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	IME varchar(50) NOT NULL,
	PREZIME varchar(50),
	KOR_IME varchar(20),
	LOZINKA varchar(30),
	TIP_KORISNIKA BIT NOT NULL,
	OBRISAN BIT NOT NULL
)
GO

